name             = "CodeLang"
grammar          = "codelang"
path_suffixes    = ["code"]
language_servers = ["codelang-lsp"]

line_comment  = "// "
block_comment = ["/*", "*/"]

indent = { tab_width = 2, unit = "  " }
